### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by avclubvids** [graphdeco-inria/nerfshop#1]
Given that NeRFShop appears to be built so closely on top of iNGP, is it safe to assume that NVIDIA's license applies to this toolset? If not, can you provide information on how this is/will be licensed?

**Comment by clementjambon** [comment]
Hello @avclubvids 
Indeed it does! For more information please refer to the updated [LICENSE file ](https://github.com/graphdeco-inria/nerfshop/blob/492631642959138406c43e219fb484389103c48d/README.md).
