### ISSUE TITLE
Crash when try to compute the approximate proxy after region growing

### ISSUE THREAD

**Issue by louhz** [graphdeco-inria/nerfshop#11]
Hi, Thanks for your great work!
However, when i try to compute the approximate proxy after region growing , the system break and the following error drops:

21:05:19 INFO     #vertices=9622 #triangles=19244
Failed to compute progressive hulls...
Computed proxy with 56 vertices and 112 triangles
Segmentation fault (core dumped)

I guess this error was raised since I set up two many points for grow region?

**Comment by louhz** [comment]
Hi, this error shows up again when i try to switch the operator visualization type from growing region to compute tetrahedron mesh, and the following error pumps 


#vertices=7926 #triangles=15832
Failed to compute progressive hulls...
Computed proxy with 76 vertices and 132 triangles
Computed tet mesh with 32 vertices, 64 triangles and 57 tets
Failed to compute progressive hulls...
Computed proxy with 76 vertices and 132 triangles
Failed to compute progressive hulls...
Computed proxy with 76 vertices and 132 triangles
Computed tet mesh with 32 vertices, 64 triangles and 57 tets
Failed to compute progressive hulls...
Computed proxy with 76 vertices and 132 triangles
Computed tet mesh with 32 vertices, 64 triangles and 57 tets
Failed to compute progressive hulls...
Computed proxy with 76 vertices and 132 triangles
Computed tet mesh with 32 vertices, 64 triangles and 57 tets
Failed to compute progressive hulls...
Computed proxy with 76 vertices and 132 triangles
Computed tet mesh with 32 vertices, 64 triangles and 57 tets
Reprojected 229 rays
13:41:02 INFO     #vertices=4762 #triangles=9504
Computed proxy with 60 vertices and 100 triangles
Computed tet mesh with 26 vertices, 48 triangles and 38 tets
Segmentation fault (core dumped)


After some experiments, I realize that the error only pumps when I use the Scribble-based selection and the point selection is very sparse. 

So my system setup is ubuntu 20.04 + rtx3090 and I am using build from source.

**Comment by Snosixtyboo** [comment]
Hi, we found two issues where the code may try to use an uninitialized pointer. This may have been the issues that you saw, our fixes are in the hanging_issues branch and we will merge into the main and recreate the executables after a code review.
