### ISSUE TITLE
no-gui training keeps running...

### ISSUE THREAD

**Issue by ibrahimrazu** [graphdeco-inria/nerfshop#15]
Hi,
Thanks a lot for your code. I was checking the model with benchmark fox nerf images. It appears to be the training doesnt stop even after 30 hours. I've kept everything default. 
Is there any trick i should follow? Thanks :)

**Comment by clementjambon** [comment]
Training never stops automatically. Simply click on "Stop Training" in the training window...

**Comment by ibrahimrazu** [comment]
@clementjambon thanks a lot for your reply. Actually i'm trying first time at the server. so was passing this: 
./build/nerfshop --scene <path> --no-gui
Is there any way to control the --no-gui version and still getting the ckpt file stored?
