### ISSUE TITLE
When I did git clone --recursive <link to repository>, I got the connection refused.

### ISSUE THREAD

**Issue by tetsu-kikuchi** [graphdeco-inria/nerfshop#25]
Hello.  When I did 
`git clone --recursive https://github.com/graphdeco-inria/nerfshop.git`
the connection was refused, such as 
```
Cloning into '/mnt/nerfshop/dependencies/meshfix'...
fatal: unable to access 'https://gitlab.inria.fr/cjambon/meshfix.git/': Failed to connect to gitlab.inria.fr port 443: Connection refused
fatal: clone of 'https://gitlab.inria.fr/cjambon/meshfix.git' into submodule path '/mnt/nerfshop/dependencies/meshfix' failed
```
and
```
Cloning into '/mnt/nerfshop/dependencies/tiny-cuda-nn'...
fatal: unable to access 'https://gitlab.inria.fr/cjambon/tcnn-pyngp.git/': Failed to connect to gitlab.inria.fr port 443: Connection refused
fatal: clone of 'https://gitlab.inria.fr/cjambon/tcnn-pyngp.git' into submodule path '/mnt/nerfshop/dependencies/tiny-cuda-nn' failed
```

This seems not due to my network environment, because in the same environment, I was able to git clone instant-NGP, 
`git clone --recursive https://github.com/nvlabs/instant-ngp`
without any errors.

I am working in a Docker container (pytorch/pytorch) in a Ubuntu server.  

Could you give any help?  Sorry if this question is too general or too novice.

**Comment by grgkopanas** [comment]
seems like gitlab.inria.fr is down right now. This might be the problem

**Comment by tetsu-kikuchi** [comment]
After 12 hours later, I retried the same git clone ... , and everything worked fine (except a tremendous amount of warning messages...).  I was able to install nerfshop and now I am enjoying its GUI !
As suggested, the reason of the connection error seems to be temporal down of gitlab.inria.fr.
Thank you and sorry for bothering you.

**Comment by tetsu-kikuchi** [comment]
The issue got solved.  the reason of the connection error seems to be temporal down of gitlab.inria.fr.
