### ISSUE TITLE
Shift-select is "sticky"

### ISSUE THREAD

**Issue by avclubvids** [graphdeco-inria/nerfshop#3]
The shift-select box starts drawing when you press the shift key instead of when you click the mouse (a more normal/expected shift-select behavior) so you have to either re-draw your selection if it started drawing in a strange place, or you end up making several smaller-than-intended shift-select actions to get all the points you're aiming for.

**Comment by clementjambon** [comment]
Hello @avclubvids 
I refer you to the answer to this other issue: #4
