### ISSUE TITLE
Crashing whenever I try to distill

### ISSUE THREAD

**Issue by pccross** [graphdeco-inria/nerfshop#8]
Have a 3070 and running the .exe.  I'm able to create the cage around my subject, however, when I select distill, it acts like training has started, but the application locks up.    This happens consistently.   For reference, I'm using the standard fox scene included with instantNerf.

**Comment by Snosixtyboo** [comment]
Hi, thanks for bringing this up! Unfortunately, I can't replicate this error, distilling edits in the fox scene with the .exe works fine for me. Is there any chance we could set up a meeting to demonstrate the issue live?

**Comment by Snosixtyboo** [comment]
Hi, we believe we found and fixed the bug. You may try the fixes in the hanging_issues branch. We will merge them into the main and recreate the .exe files after a code review :)
