### ISSUE TITLE
Manual bounding-box style cage?

### ISSUE THREAD

**Issue by avclubvids** [graphdeco-inria/nerfshop#9]
The paint/project/grow/proxy workflow is great, but I think there is a huge value to also having the option to create a cubic proxy mesh that we can translate/scale/rotate to quickly vanish floaters and/or grab parts of a NeRF that are easy to put in a bounding box, but perhaps harder to fully select using the paint/project/grow/proxy workflow.

**Comment by Snosixtyboo** [comment]
Hi, we now added this behavior with the ```hanging_issues``` branch. A "box cage" can be spawned directly in cage refinement mode. So the box can first be transformed at will and only turns into a proxy cage when "Compute Proxy" is clicked. We will soon merge this into the main and recompile the executables. Thanks for the idea!
